[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = [
  "python3.10 -m venv /opt/venv",
  "source /opt/venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "python3.10 app.py"
